# Generated by Django 4.0.3 on 2022-05-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('picture_url', models.URLField(null=True)),
            ],
        ),
    ]
