# Generated by Django 4.0.3 on 2022-05-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'ordering': ('model',)},
        ),
    ]
