# Generated by Django 4.0.3 on 2022-05-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0004_binvo_shoe_shoe_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_bin',
        ),
    ]
